apiVersion: v1
data:
  nginx-config.conf: "server {\n    listen 80;\n    index index.php;\n    server_name
    php-docker.local;\n    root /opt/kimai/public;\n\n    # cache static asset files\n
    \   location ~* \\.(ico|css|js|gif|jpe?g|png)(\\?[0-9]+)?$ {\n            expires
    max;\n            log_not_found off;\n    }\n\n    # for health checks\n    location
    /health {\n        return 200 'alive';\n        add_header Content-Type text/plain;\n
    \   }\n\n    location / {\n        # try to serve file directly, fallback to index.php\n
    \       try_files $uri $uri/ /index.php$is_args$args;\n    }\n    \n    location
    ~ ^/index\\.php(/|$) {\n        fastcgi_pass kimai:9000;\n        fastcgi_split_path_info
    ^(.+\\.php)(/.*)$;\n        include fastcgi_params;\n\n        # optionally set
    the value of the environment variables used in the application\n        # fastcgi_param
    APP_ENV prod;\n        # fastcgi_param APP_SECRET <app-secret-id>;\n        #
    fastcgi_param DATABASE_URL \"mysql://db_user:db_pass@mysql:3306/db_name\";\n\n
    \       # When you are using symlinks to link the document root to the\n        #
    current version of your application, you should pass the real\n        # application
    path instead of the path to the symlink to PHP\n        # FPM.\n        # Otherwise,
    PHP's OPcache may not properly detect changes to\n        # your PHP files (see
    https://github.com/zendtech/ZendOptimizerPlus/issues/126\n        # for more information).\n
    \       fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;\n        fastcgi_param
    DOCUMENT_ROOT $realpath_root;\n        # Prevents URIs that include the front
    controller. This will 404:\n        # http://domain.tld/index.php/some-path\n
    \       # Remove the internal directive to allow URIs like this\n        internal;\n
    \   }\n}"
kind: ConfigMap
metadata:
  name: nginx-config

